name: Continuous Integration on pull requests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: npm install
      - run: yarn install
      - run: yarn lint
